services:
 postgres:
  image: postgres
  container_name: postgres
  restart: always
  environment:
   POSTGRES_DB: example
   POSTGRES_PASSWORD: root
   POSTGRES_USER: admin
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data
   - ./init:/docker-entrypoint-initdb.d
  networks:
   - catalog
 minio:
  image: quay.io/minio/minio:latest
  command: server /data --console-address ":9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
    MINIO_STS_DURATION: "720h"
    MINIO_STS_EXPIRY: "720h"
  volumes:
    - minio_data:/data
  ports:
    - "9000:9000" 
    - "9001:9001" 
  restart: unless-stopped
  networks:
   - catalog
 catalog:
  container_name: catalog
  image: catalog
  restart: always
  environment:
   SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/example?createDatabaseIfNotExist=true
   SPRING_DATASOURCE_USERNAME: admin
   SPRING_DATASOURCE_PASSWORD: root
  ports:
   - "8080:8080"
  networks:
   - catalog
  depends_on:
   - postgres
volumes:
 postgres_data:
 minio_data:
networks:
 catalog:
